---
- name: "Install powertools dependencies: dnf-plugins-core"
  shell: "pkcon install -y dnf-plugins-core | true"
- name: "Install dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ APP_DEPENDENCIES }}"
- name: "Create the directory {{ APP_SRC }}"
  file:
    name: "{{ APP_SRC }}"
    state: directory
- name: "Check for the README file {{ APP_README }}"
  stat:
    path: "{{ APP_README }}"
  register: APP_README_PATH
- name: "Clone the {{ APP_REPO }} source code into {{ APP_SRC }}"
  git:
    repo: "{{ APP_REPO }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  when: not APP_README_PATH.stat.exists
- name: "Run the autogen.sh script in {{ APP_SRC }}"
  shell:
    cmd: ./autogen.sh
    chdir: "{{ APP_SRC }}"
- name: "Run the configure script in {{ APP_SRC }}"
  shell:
    cmd: "./configure --prefix {{ APP_PREFIX }}"
    chdir: "{{ APP_SRC }}"
- name: "Run the make script in {{ APP_SRC }}"
  shell:
    cmd: make
    chdir: "{{ APP_SRC }}"
- name: "Run the make install script in {{ APP_SRC }}"
  shell:
    cmd: make install
    chdir: "{{ APP_SRC }}"
- name: "Create the launcher {{ APP_DESKTOP }}"
  template:
    src: app.desktop
    dest: "{{ APP_DESKTOP }}"
    mode: 0775

